INSERT INTO public.tags_mapping (partner, metroprop_tag_id, partner_tag_id, partner_tag_name)
VALUES
('tokko', 1, 1, 'Agua Corriente'),
('tokko', 2, 2, 'Cloaca'),
('tokko', 3, 3, 'Gas Natural'),
('tokko', 4, 4, 'Internet'),
('tokko', 5, 5, 'Electricidad'),
('tokko', 6, 6, 'Pavimento'),
('tokko', 7, 7, 'Teléfono'),
('tokko', 8, 8, 'Cable'),
('tokko', NULL, 1145, 'Pozo negro'),
('tokko', NULL, 1443, 'Agua Potable'),
('tokko', NULL, 1477, 'Gas Envasado'),
('tokko', NULL, 1478, 'Gas Industrial'),
('tokko', NULL, 1499, 'Energia trifasica'),
('tokko', 4, 1507, 'Wifi'),
('tokko', NULL, 1540, 'Losa radiante general'),
('tokko', NULL, 1573, 'Alumbrado público'),
('tokko', NULL, 1574, 'Biodigestor'),
('tokko', NULL, 1575, 'TV por Satélite'),
('tokko', NULL, 1576, 'Celular'),
('tokko', NULL, 1586, 'Red de desagües pluviales'),
('tokko', NULL, 1587, 'Instalación eléctrica subterránea.'),
('tokko', NULL, 1628, 'Encargado'),
('tokko', NULL, 1629, 'Cadete'),
('tokko', NULL, 1630, 'Garagistas'),
('tokko', NULL, 1631, 'Servicio de playa'),
('tokko', NULL, 1632, 'Servicio de Mantenimiento'),
('tokko', NULL, 1633, 'TV Cable en el edificio'),
('tokko', NULL, 1669, 'Piletero'),
('tokko', NULL, 1670, 'Passenger boat'),
('tokko', NULL, 1901, 'Monoambiente'),
('tokko', NULL, 1902, 'Ático con baño'),
('tokko', NULL, 1903, 'Ático con chimenea'),
('tokko', NULL, 1904, 'Baño grande'),
('tokko', NULL, 1905, 'Baño boudoir'),
('tokko', NULL, 1906, 'Baño con ducha de vidrio'),
('tokko', NULL, 1907, 'Baño con doble ducha'),
('tokko', NULL, 1908, 'Baño con jacuzzi'),
('tokko', NULL, 1909, 'Baño con sauna'),
('tokko', NULL, 1910, 'Sala de guardería'),
('tokko', 51, 1911, 'Sala de juguetes'),
('tokko', 51, 1912, 'Sala de naipes'),
('tokko', 51, 1913, 'Casa de muñecas'),
('tokko', NULL, 1914, 'Casa del árbol'),
('tokko', NULL, 1915, 'Casa trasera'),
('tokko', NULL, 1916, 'Cabaña'),
('tokko', 13, 1917, 'Cocina grande'),
('tokko', 13, 1918, 'Cocina compartida'),
('tokko', 13, 1919, 'Cocina con isla'),
('tokko', NULL, 1920, 'Cocina con lavadero integrado'),
('tokko', NULL, 1921, 'Cocina con pasa-platos'),
('tokko', NULL, 1922, 'Cocina con cafetería'),
('tokko', NULL, 1923, 'Cocina concepto abierto'),
('tokko', NULL, 1924, 'Cocina integrada'),
('tokko', 13, 1925, 'Cocina equipada'),
('tokko', 13, 1926, 'Cocina gourmet'),
('tokko', 13, 1927, 'Cocina independiente'),
('tokko', NULL, 1928, 'Cocina industrial'),
('tokko', NULL, 1929, 'Cocina a medida'),
('tokko', NULL, 1930, 'Dormitorio de huéspedes'),
('tokko', NULL, 1931, 'Pequeño anexo'),
('tokko', NULL, 1932, 'Anexo con parrilla'),
('tokko', NULL, 1933, 'Área de café'),
('tokko', NULL, 1934, 'Espacio cultural'),
('tokko', NULL, 1935, 'Área social'),
('tokko', NULL, 1936, 'Área de descanso'),
('tokko', NULL, 1937, 'Área juvenil'),
('tokko', NULL, 1938, 'Área infantil'),
('tokko', NULL, 1939, 'Área adolescente'),
('tokko', NULL, 1940, 'Área de arte y manualidades'),
('tokko', NULL, 1941, 'Área de pub'),
('tokko', NULL, 1942, 'Espacio zen'),
('tokko', 51, 1943, 'Estudio de música'),
('tokko', 51, 1944, 'Estudio de pilates'),
('tokko', 51, 1945, 'Centro de juegos'),
('tokko', 22, 1946, 'Entre piso con oficina'),
('tokko', 22, 1947, 'Centro de oficinas'),
('tokko', NULL, 1948, 'Taller'),
('tokko', NULL, 1949, 'Observatorio'),
('tokko', NULL, 1950, 'Sala de belleza'),
('tokko', NULL, 1951, 'Salón de masaje'),
('tokko', 51, 1952, 'Sala de póker'),
('tokko', 51, 1953, 'Sala de pool'),
('tokko', 51, 1954, 'Sala de video'),
('tokko', NULL, 1955, 'Salón de eventos'),
('tokko', NULL, 1956, 'Sala de recepción'),
('tokko', NULL, 1957, 'Salón(es) de convenciones'),
('tokko', 58, 1958, 'SUM con parrilla'),
('tokko', 58, 1959, 'SUM privado'),
('tokko', 51, 1960, 'Sala de juegos con parrilla'),
('tokko', 51, 1961, 'Lounge deportivo'),
('tokko', 51, 1962, 'Taberna'),
('tokko', NULL, 2051, 'Ambientes equipados y decorados'),
('tokko', NULL, 2053, 'Antesala'),
('tokko', NULL, 2060, 'Baños para hombres y mujeres'),
('tokko', NULL, 2064, 'Baño de hombres'),
('tokko', NULL, 2065, 'Baño de mujeres'),
('tokko', NULL, 2066, 'Baño compartido'),
('tokko', NULL, 2078, 'Área cercada'),
('tokko', NULL, 2082, 'Parrilla integrada a cocina'),
('tokko', NULL, 2083, 'Áreas de parrilla compartidas'),
('tokko', NULL, 2087, 'Área de entrenamiento funcional'),
('tokko', NULL, 2089, 'Vestidor de hombres'),
('tokko', NULL, 2090, 'Vestidores de hombres y mujeres'),
('tokko', NULL, 2091, 'Vestidor de mujeres'),
('tokko', NULL, 2096, 'Pasillo con placard'),
('tokko', NULL, 2100, 'Cocina con cerámicos'),
('tokko', NULL, 2101, 'Suite Jack y Jill'),
('tokko', NULL, 2120, 'Sector náutico'),
('tokko', NULL, 2121, 'Sector de mate'),
('tokko', NULL, 2122, 'Área de entregas'),
('tokko', NULL, 2123, 'Área funcional'),
('tokko', NULL, 2124, 'Área de mujeres'),
('tokko', NULL, 2125, 'Área de hamacas'),
('tokko', NULL, 2126, 'Área para adultos mayores'),
('tokko', NULL, 2136, 'Living con pérgola'),
('tokko', NULL, 2144, 'Galería pluvial'),
('tokko', NULL, 2145, 'Galería de arte'),
('tokko', NULL, 2157, 'Hall de triple altura'),
('tokko', NULL, 2158, 'Hall de entrada decorado'),
('tokko', NULL, 2183, 'Toilette con piso calefaccionado'),
('tokko', NULL, 2188, 'Sala con parrilla'),
('tokko', NULL, 2189, 'Sala gourmet'),
('tokko', NULL, 2200, 'Área de juegos múltiples'),
('tokko', NULL, 2204, 'Nichos esculpidos en baño'),
('tokko', NULL, 2211, 'Patio de servicio'),
('tokko', NULL, 2212, 'Patio de maniobras'),
('tokko', NULL, 2234, 'Desagüe para triturador de cocina'),
('tokko', NULL, 2235, 'Toma de TV en baño'),
('tokko', 57, 2237, 'Solárium en la pileta'),
('tokko', NULL, 2263, 'Dormitorio(s) con bañera'),
('tokko', NULL, 2264, 'Dormitorio(s) con placard'),
('tokko', NULL, 2265, 'Dormitorio(s) con piso flotante'),
('tokko', NULL, 2266, 'Dormitorio(s) simple(s)'),
('tokko', NULL, 2274, 'Cafetería'),
('tokko', NULL, 2281, 'Habitación de Servicio'),
('tokko', NULL, 2282, 'Sala de entregas'),
('tokko', NULL, 2283, 'Living con barra'),
('tokko', NULL, 2284, 'Grandes livings y comedores'),
('tokko', NULL, 2285, 'Sala de estética'),
('tokko', NULL, 2286, 'Sala de herramientas'),
('tokko', NULL, 2287, 'Comedor con parrilla'),
('tokko', NULL, 2288, 'Sala de pintura'),
('tokko', 51, 2289, 'Sala de ping pong'),
('tokko', NULL, 2290, 'Sala íntima'),
('tokko', NULL, 2291, 'Sala grande de 2 ambientes'),
('tokko', NULL, 2292, 'Sala grande de 3 ambientes'),
('tokko', NULL, 2293, 'Sala grande de 4 ambientes'),
('tokko', NULL, 2294, 'Sala grande de 6 ambientes'),
('tokko', NULL, 2295, 'Sala con aislación acústica'),
('tokko', NULL, 2296, 'Sala con placard'),
('tokko', NULL, 2298, 'Sala integrada a cocina'),
('tokko', NULL, 2299, 'Hall con parrilla'),
('tokko', NULL, 2302, 'Semisuites'),
('tokko', NULL, 2304, 'Sensor de presencia en áreas comunes'),
('tokko', NULL, 2309, 'Suite con muebles a medida'),
('tokko', NULL, 2310, 'Suite con placard y bañera'),
('tokko', NULL, 2311, 'Suite con placard e hidromasaje'),
('tokko', NULL, 2312, 'Suite con doble bacha'),
('tokko', NULL, 2313, 'Suite con chimenea'),
('tokko', NULL, 2314, 'Suite principal con placard'),
('tokko', NULL, 2315, 'Suite principal con hidromasaje'),
('tokko', 25, 2324, 'Terraza con parrilla'),
('tokko', NULL, 2325, 'Terraza con techo retráctil'),
('tokko', 25, 2326, 'Terraza con hidromasaje'),
('tokko', NULL, 2327, 'Terraza con jacuzzi'),
('tokko', 25, 2328, 'Terraza con pileta'),
('tokko', NULL, 2329, 'Terraza con jardín'),
('tokko', 9, 9, 'Altillo'),
('tokko', 10, 10, 'Balcón'),
('tokko', 11, 11, 'Baulera'),
('tokko', 13, 12, 'Cocina'),
('tokko', 14, 14, 'Comedor diario'),
('tokko', 15, 15, 'Dependencia'),
('tokko', 22, 17, 'Oficina'),
('tokko', 18, 18, 'Hall'),
('tokko', 19, 19, 'Jardín'),
('tokko', 20, 20, 'Lavadero'),
('tokko', 21, 22, 'Living comedor'),
('tokko', 23, 23, 'Patio'),
('tokko', 24, 24, 'Sótano'),
('tokko', 25, 25, 'Terraza'),
('tokko', 26, 26, 'Toilette'),
('tokko', 27, 27, 'Vestidor'),
('tokko', 13, 87, 'Cocina Americana'),
('tokko', 25, 114, 'Terraza Cubierta'),
('tokko', NULL, 151, 'Apartamento de Invitados'),
('tokko', 16, 163, 'Escritorio'),
('tokko', 46, 164, 'Pileta Cubierta'),
('tokko', 12, 168, 'Biblioteca'),
('tokko', NULL, 192, 'Despensa'),
('tokko', NULL, 475, 'Apartamento Independiente'),
('tokko', NULL, 1490, 'Vestuarios Femeninos'),
('tokko', NULL, 1491, 'Vestuarios Masculinos'),
('tokko', NULL, 1504, 'Baño de servicio'),
('tokko', 17, 1516, 'Galería'),
('tokko', NULL, 1523, 'Palier'),
('tokko', 10, 1555, 'Balcón terraza'),
('tokko', 51, 1558, 'Sala de juegos'),
('tokko', NULL, 1658, 'Dependencia con baño'),
('tokko', NULL, 1666, 'Galpón'),
('tokko', NULL, 1793, 'Sala de reuniones'),
('tokko', NULL, 1810, 'Baño auxiliar'),
('tokko', 13, 1840, 'Cocina equipada'),
('tokko', 13, 1847, 'Cocina independiente'),
('tokko', NULL, 1859, 'Dormitorio principal'),
('tokko', NULL, 1964, 'Aire acondicionado'),
('tokko', NULL, 1965, 'Climatizado'),
('tokko', NULL, 1966, 'Suministro de agua compartido'),
('tokko', NULL, 1968, 'Bicicletas compartidas'),
('tokko', NULL, 1969, 'Sistema de bicicletas compartidas'),
('tokko', NULL, 1970, 'Biometría'),
('tokko', NULL, 1971, 'Captación de energía solar'),
('tokko', NULL, 1972, 'Cargador para vehículo eléctrico'),
('tokko', NULL, 1973, 'Garaje automatizado'),
('tokko', NULL, 1974, 'Sector de lavado de autos'),
('tokko', NULL, 1975, 'Ascensor por huella digital'),
('tokko', NULL, 1976, 'Ascensor panorámico'),
('tokko', NULL, 1977, 'Ascensor vehicular'),
('tokko', NULL, 1978, 'Ascensor privado'),
('tokko', NULL, 1979, 'Ascensor adaptado'),
('tokko', NULL, 1980, 'Conserjería de 7 a 23 hs'),
('tokko', NULL, 1981, 'Conserjería remota'),
('tokko', NULL, 1982, 'Conserjería virtual'),
('tokko', NULL, 1983, 'Portero eléctrico'),
('tokko', NULL, 1984, 'Seguridad monitorizada'),
('tokko', NULL, 1985, 'Seguridad vehicular'),
('tokko', NULL, 1986, 'Sistema de cámaras'),
('tokko', NULL, 1987, 'Sistema de Seguridad'),
('tokko', NULL, 1988, 'Sistema de prevención de incendios'),
('tokko', NULL, 1989, 'Sistema de monitoreo'),
('tokko', NULL, 1990, 'Sistema de calefacción'),
('tokko', NULL, 1991, 'Sistema de calefacción solar'),
('tokko', NULL, 1992, 'Sistema de generación de energía fotovoltaica'),
('tokko', NULL, 1993, 'Sistema de riego'),
('tokko', NULL, 1994, 'Sistema de riego de jardín'),
('tokko', NULL, 1995, 'Sistema de captación de aguas'),
('tokko', NULL, 1996, 'Sistema de recolección de aguas'),
('tokko', NULL, 1997, 'Sistema de sonido'),
('tokko', NULL, 1998, 'Sonido ambiental en áreas comunes'),
('tokko', NULL, 1999, 'Servicios pay-per-use'),
('tokko', NULL, 2000, 'Room service'),
('tokko', NULL, 2001, 'Monopatines eléctricos compartidos'),
('tokko', NULL, 2002, 'Café internet'),
('tokko', NULL, 2003, 'Minimercado'),
('tokko', NULL, 2004, 'Máquinas expendedoras'),
('tokko', NULL, 2054, 'Antena compartida'),
('tokko', NULL, 2058, 'Calefacción eléctrica y a gas'),
('tokko', 51, 2062, 'Pista de bowling'),
('tokko', 35, 2070, 'Cancha de césped sintético'),
('tokko', 35, 2071, 'Cancha de fútbol infantil'),
('tokko', 35, 2072, 'Cancha de fútbol de arena'),
('tokko', 35, 2073, 'Cancha de Bochas'),
('tokko', NULL, 2107, 'Ascensor con recuperación de energía'),
('tokko', NULL, 2114, 'Entrada principal y de servicio'),
('tokko', NULL, 2115, 'Equipo de calefacción'),
('tokko', NULL, 2128, 'Espejo de agua'),
('tokko', NULL, 2132, 'Valet parking'),
('tokko', NULL, 2133, 'Estacionamiento de vehículos'),
('tokko', NULL, 2134, 'Estacionamiento rotativo'),
('tokko', NULL, 2135, 'Estación de servicio'),
('tokko', NULL, 2149, 'Gas por cañería'),
('tokko', NULL, 2150, 'Gas central'),
('tokko', NULL, 2156, 'Garita con seguridad'),
('tokko', NULL, 2160, 'Iluminación automatizada'),
('tokko', NULL, 2161, 'Iluminación LED'),
('tokko', NULL, 2162, 'Iluminación inteligente'),
('tokko', NULL, 2163, 'Infraestructura para calefactor'),
('tokko', NULL, 2164, 'Infraestructura para aspiradora central'),
('tokko', NULL, 2165, 'Infraestructura para automatización'),
('tokko', NULL, 2166, 'Infraestructura para campana extractora'),
('tokko', NULL, 2167, 'Infraestructura para desempañador de espejos'),
('tokko', NULL, 2168, 'Infraestructura para ascensor'),
('tokko', NULL, 2169, 'Infraestructura para persianas'),
('tokko', NULL, 2170, 'Infraestructura para sauna'),
('tokko', NULL, 2171, 'Infraestructura para sistema de sonido'),
('tokko', NULL, 2172, 'Infraestructura para toallero eléctrico'),
('tokko', NULL, 2186, 'Lavadero con bacha de agua caliente'),
('tokko', NULL, 2194, 'Marina para lanchas'),
('tokko', NULL, 2195, 'Medidores individuales de gas y agua'),
('tokko', NULL, 2209, 'Parque de césped'),
('tokko', NULL, 2215, 'Muelle'),
('tokko', NULL, 2218, 'Piscina infinita'),
('tokko', NULL, 2219, 'Piscina con bar'),
('tokko', NULL, 2220, 'Piscina con hidromasaje'),
('tokko', NULL, 2221, 'Pileta para niños'),
('tokko', NULL, 2225, 'Pista para correr'),
('tokko', NULL, 2226, 'Pista para correr/caminar'),
('tokko', NULL, 2227, 'Pista de patinaje'),
('tokko', NULL, 2228, 'Pista de aterrizaje'),
('tokko', NULL, 2229, 'Carril para patinaje'),
('tokko', NULL, 2231, 'Plaza pequeña'),
('tokko', NULL, 2233, 'Punto de agua caliente'),
('tokko', NULL, 2248, 'Edificio sin ascensor'),
('tokko', NULL, 2249, 'Pre-instalación para ascensor'),
('tokko', NULL, 2250, 'Pileta y sauna privados'),
('tokko', NULL, 2252, 'Proyecto de automatización'),
('tokko', NULL, 2253, 'Proyecto lumínico'),
('tokko', NULL, 2254, 'Buffer de seguridad'),
('tokko', NULL, 2255, 'Cancha de beach tennis'),
('tokko', NULL, 2256, 'Cancha de césped'),
('tokko', NULL, 2257, 'Cancha de césped sintético'),
('tokko', NULL, 2258, 'Cancha de arena'),
('tokko', NULL, 2259, 'Cancha de futsal'),
('tokko', NULL, 2260, 'Cancha de bádminton'),
('tokko', NULL, 2261, 'Cancha de pickleball'),
('tokko', NULL, 2262, 'Cancha recreativa'),
('tokko', NULL, 2272, 'Red de tratamiento de efluentes'),
('tokko', NULL, 2278, 'Reutilización de agua de lluvia'),
('tokko', NULL, 2301, 'Sauna y jacuzzi'),
('tokko', NULL, 2303, 'Sensor perimetral'),
('tokko', NULL, 2306, 'Sistema de esclusa de aire'),
('tokko', NULL, 2307, 'Sistema de iluminación solar'),
('tokko', NULL, 2308, 'Sistema de presurización'),
('tokko', NULL, 2332, 'Tirolesa'),
('tokko', NULL, 2336, 'Embarcadero'),
('tokko', NULL, 2337, 'Sendero de trekking'),
('tokko', NULL, 2341, 'Estacionamiento para personas con movilidad reducida'),
('tokko', NULL, 2343, 'Tendedero compartido'),
('tokko', 28, 28, 'Aire Acondicionado individual'),
('tokko', 29, 29, 'Alarma'),
('tokko', 30, 30, 'Amoblado'),
('tokko', 32, 31, 'Calefacción'),
('tokko', 35, 32, 'Centro de deportes'),
('tokko', 39, 33, 'Gimnasio'),
('tokko', 40, 34, 'Hidromasaje'),
('tokko', 44, 35, 'Parrilla'),
('tokko', 48, 36, 'Quincho'),
('tokko', 51, 38, 'Sala de juegos'),
('tokko', 52, 39, 'Sauna'),
('tokko', 57, 40, 'Solarium'),
('tokko', 58, 41, 'SUM'),
('tokko', 53, 42, 'Seguridad'),
('tokko', NULL, 43, 'Al lago'),
('tokko', NULL, 44, 'Al rio'),
('tokko', NULL, 45, 'Al bosque'),
('tokko', NULL, 46, 'Apto mascotas'),
('tokko', NULL, 47, 'Apto profesional'),
('tokko', 42, 48, 'Lote Interno'),
('tokko', 50, 49, 'Ruta'),
('tokko', 45, 50, 'Perimetral'),
('tokko', 46, 51, 'Pileta'),
('tokko', 49, 52, 'Riego automático'),
('tokko', NULL, 53, 'Vista al golf'),
('tokko', NULL, 81, 'Acceso a la playa'),
('tokko', NULL, 86, 'Carpintería de aluminio'),
('tokko', 32, 101, 'Calefacción central'),
('tokko', 46, 106, 'Pileta Comunitaria'),
('tokko', NULL, 123, 'Doble Acristalamiento'),
('tokko', NULL, 132, 'Detector de Incendios'),
('tokko', NULL, 136, 'Suelo Radiante'),
('tokko', 31, 147, 'Caldera'),
('tokko', NULL, 149, 'Generador'),
('tokko', NULL, 180, 'Estilo Moderno'),
('tokko', NULL, 181, 'Vista a la montaña'),
('tokko', NULL, 188, 'Una Planta'),
('tokko', 35, 190, 'Cancha de Paddle'),
('tokko', 47, 203, 'Preinstalación de aire acondicionado'),
('tokko', NULL, 204, 'Preinstalación de Calefacción'),
('tokko', 53, 209, 'Seguridad Privada'),
('tokko', NULL, 220, 'Estilo Rústico'),
('tokko', NULL, 232, 'Placa Solar de Agua'),
('tokko', NULL, 259, 'Video Cámaras'),
('tokko', NULL, 263, 'Depósito de Agua'),
('tokko', NULL, 267, 'Bodega'),
('tokko', NULL, 270, 'Carpintería'),
('tokko', NULL, 471, 'Entrada automática'),
('tokko', NULL, 494, 'Con proyecto de construccion'),
('tokko', NULL, 495, 'Parquet'),
('tokko', NULL, 946, 'Ubicación tranquila'),
('tokko', 53, 948, 'Guarda de seguridad'),
('tokko', NULL, 959, 'Corta distancia a pie centro'),
('tokko', NULL, 965, 'Atico'),
('tokko', NULL, 997, 'Ubicación residencial'),
('tokko', NULL, 1002, 'Circuito Cerrado TV'),
('tokko', NULL, 1005, 'Helipuerto'),
('tokko', NULL, 1008, 'Sistema instalado de música'),
('tokko', NULL, 1014, 'Frigorífico'),
('tokko', NULL, 1021, 'Armarios Empotrados'),
('tokko', 36, 1030, 'Cochera subterránea'),
('tokko', NULL, 1040, 'Caja Fuerte'),
('tokko', NULL, 1064, 'Mosquitera'),
('tokko', NULL, 1065, 'Persianas'),
('tokko', NULL, 1082, 'Termo de gas'),
('tokko', NULL, 1084, 'Rejas de seguridad'),
('tokko', NULL, 1087, 'Agua sin conectar'),
('tokko', NULL, 1088, 'Electricidad sin conectar'),
('tokko', NULL, 1092, 'Toldos'),
('tokko', NULL, 1093, 'Necesita algunas reformas'),
('tokko', NULL, 1108, 'Puerta blindada'),
('tokko', NULL, 1117, 'Gas Butano'),
('tokko', NULL, 1176, 'Fuente natural'),
('tokko', NULL, 1224, 'Termo eléctrico'),
('tokko', NULL, 1230, 'Toma de gas ciudad'),
('tokko', NULL, 1233, 'Posibilidad instalar ascensor'),
('tokko', 38, 1248, 'En construcción'),
('tokko', NULL, 1255, 'Ventanas de aluminio'),
('tokko', NULL, 1257, 'Ventanas doble acristalamiento'),
('tokko', NULL, 1259, 'Ventanas de madera'),
('tokko', NULL, 1268, 'Descalcificadora'),
('tokko', NULL, 1291, 'Zona de parrillas'),
('tokko', NULL, 1296, 'Amarras'),
('tokko', NULL, 1297, 'Ascensor de servicio'),
('tokko', NULL, 1299, 'Puente grúa'),
('tokko', NULL, 1300, 'Restaurante'),
('tokko', NULL, 1301, 'Vivienda Portero'),
('tokko', NULL, 1314, 'Puerta de garaje automática'),
('tokko', NULL, 1319, 'Pisos de concreto'),
('tokko', NULL, 1322, 'Portones eléctricos'),
('tokko', NULL, 1326, 'Calle de grava'),
('tokko', NULL, 1327, 'Techos altos'),
('tokko', NULL, 1328, 'Entreplanta'),
('tokko', NULL, 1329, 'Extractor de humo'),
('tokko', NULL, 1330, 'Aislamiento acústico'),
('tokko', NULL, 1341, 'Plancha Industrial'),
('tokko', NULL, 1348, 'Cortinas'),
('tokko', NULL, 1360, 'Horno de pizza'),
('tokko', NULL, 1369, 'Horno de pan'),
('tokko', NULL, 1374, 'Edificio de Perímetro Libre'),
('tokko', 43, 1390, 'Luminoso'),
('tokko', NULL, 1418, 'Acceso doble'),
('tokko', NULL, 1449, 'Parcela en esquina'),
('tokko', NULL, 1451, 'Terreno apto para cultivo'),
('tokko', NULL, 1456, 'Laguna interior'),
('tokko', NULL, 1460, 'Zona apta para turismo'),
('tokko', NULL, 1461, 'Frente a carretera'),
('tokko', NULL, 1475, 'Comedor para personal'),
('tokko', NULL, 1484, 'Portón Levadizo'),
('tokko', NULL, 1485, 'Techo de Cabriada'),
('tokko', NULL, 1486, 'Techo de Chapa'),
('tokko', NULL, 1487, 'Techo de Fibrocemento'),
('tokko', NULL, 1488, 'Techo de Hormigón'),
('tokko', NULL, 1489, 'Techo Parabólico'),
('tokko', NULL, 1493, 'Fuerza motriz'),
('tokko', NULL, 1494, 'Montacargas'),
('tokko', NULL, 1495, 'Playa de maniobras'),
('tokko', NULL, 1500, 'Techo a dos aguas'),
('tokko', NULL, 1501, 'Amarra'),
('tokko', NULL, 1503, 'Chimenea'),
('tokko', 41, 1505, 'Laundry'),
('tokko', NULL, 1506, 'Agua Caliente Central'),
('tokko', NULL, 1508, 'Área recreativa'),
('tokko', NULL, 1509, 'Juegos para niños'),
('tokko', NULL, 1510, 'Área de relax'),
('tokko', NULL, 1511, 'Espacio para lectura'),
('tokko', NULL, 1512, 'Calefacción individual'),
('tokko', 33, 1513, 'Calefacción por aire'),
('tokko', 34, 1514, 'Calefacción por radiadores'),
('tokko', NULL, 1515, 'Vista al polo'),
('tokko', 37, 1517, 'Deck'),
('tokko', NULL, 1519, 'Seguridad nocturna'),
('tokko', NULL, 1520, 'Club House'),
('tokko', NULL, 1521, 'Polo'),
('tokko', NULL, 1522, 'Equitación'),
('tokko', 56, 1524, 'Seguridad 24hs'),
('tokko', 54, 1525, 'Seguridad de día'),
('tokko', 55, 1526, 'Seguridad portería'),
('tokko', NULL, 1527, 'Cochera opcional'),
('tokko', NULL, 1530, 'Calefón'),
('tokko', NULL, 1531, 'Calefacción por gas'),
('tokko', NULL, 1533, 'aire acondicionado central'),
('tokko', 46, 1534, 'Pileta climatizada'),
('tokko', NULL, 1536, 'Estacionamiento tarifado'),
('tokko', NULL, 1537, 'Caldera central'),
('tokko', NULL, 1538, 'Caldera individual'),
('tokko', NULL, 1539, 'Calefacción individual por debajo del suelo'),
('tokko', NULL, 1541, 'Picos de gas'),
('tokko', NULL, 1542, 'Estufas TB'),
('tokko', NULL, 1544, 'Cochera fija'),
('tokko', NULL, 1547, 'Ascensor'),
('tokko', NULL, 1548, 'Ropa blanca'),
('tokko', NULL, 1549, 'Palier privado'),
('tokko', NULL, 1550, 'Entrada de servicio'),
('tokko', NULL, 1551, 'Semi piso'),
('tokko', NULL, 1552, 'Ducha escocesa'),
('tokko', NULL, 1553, 'Cochera de cortesía'),
('tokko', NULL, 1556, 'Cerramientos de PVC'),
('tokko', NULL, 1557, 'Microcine'),
('tokko', NULL, 1559, 'Agua caliente individual'),
('tokko', NULL, 1560, 'Costa de Río'),
('tokko', NULL, 1561, 'Costa de Lago'),
('tokko', NULL, 1562, 'Bosques'),
('tokko', NULL, 1563, 'Campo Cordillera'),
('tokko', NULL, 1564, 'Campo Meseta'),
('tokko', NULL, 1565, 'Campo Costa Atlántica'),
('tokko', NULL, 1566, 'Campo productivo'),
('tokko', NULL, 1567, 'Campo vacacional'),
('tokko', NULL, 1568, 'Cordillera'),
('tokko', NULL, 1569, 'Costa Altlántica'),
('tokko', NULL, 1570, 'Meseta'),
('tokko', NULL, 1571, 'Arroyo interior'),
('tokko', NULL, 1572, 'Apto ganadería'),
('tokko', NULL, 1577, 'Vista al valle'),
('tokko', NULL, 1579, 'Arroyo lindero'),
('tokko', NULL, 1580, 'Arboleda autóctona'),
('tokko', NULL, 1582, 'Accesibilidad C/ Movilidad Reducida'),
('tokko', NULL, 1583, 'Termotanque Individual'),
('tokko', NULL, 1585, 'Vista al río'),
('tokko', NULL, 1588, 'Control de acceso'),
('tokko', NULL, 1589, 'Edificio de mantenimiento'),
('tokko', NULL, 1590, 'Edificio de oficinas administrativas'),
('tokko', NULL, 1591, 'Área de servicio'),
('tokko', NULL, 1592, 'Bicisenda'),
('tokko', NULL, 1593, 'Bascula'),
('tokko', NULL, 1594, 'Zonas Verdes'),
('tokko', NULL, 1595, 'Boulevard principal'),
('tokko', NULL, 1596, 'Barrera forestal'),
('tokko', NULL, 1598, 'Cordón cuneta'),
('tokko', NULL, 1600, 'Grúa'),
('tokko', 35, 1601, 'Cancha de Rugby'),
('tokko', NULL, 1602, 'SPA'),
('tokko', NULL, 1603, 'Apto comercial'),
('tokko', NULL, 1604, 'Campo de golf'),
('tokko', 35, 1605, 'Cancha de Hockey'),
('tokko', 35, 1606, 'Cancha de Básquet'),
('tokko', NULL, 1607, 'Bomba'),
('tokko', NULL, 1608, 'Centro de Cabalgata'),
('tokko', NULL, 1609, 'Colegio'),
('tokko', NULL, 1610, 'Cancha de Golf'),
('tokko', 35, 1611, 'Cancha de Fútbol'),
('tokko', NULL, 1612, 'Servicio de mucama'),
('tokko', 35, 1613, 'Cancha de Tenis'),
('tokko', NULL, 1614, 'Portón Corredizo'),
('tokko', NULL, 1615, 'Techo de losa'),
('tokko', NULL, 1616, 'Techo de Galvanizado'),
('tokko', NULL, 1617, 'Techo Astori'),
('tokko', NULL, 1618, 'Techo de bovedilla'),
('tokko', NULL, 1619, 'Techo premoldeado'),
('tokko', NULL, 1620, 'Techo tinglado'),
('tokko', NULL, 1621, 'Techo a 3 aguas'),
('tokko', NULL, 1622, 'Techo de zinc'),
('tokko', NULL, 1623, 'Techo de Pizarra'),
('tokko', NULL, 1624, 'Techo de teja'),
('tokko', NULL, 1625, 'Vista al mar'),
('tokko', NULL, 1626, 'Baulera individual'),
('tokko', NULL, 1627, 'Baulera general'),
('tokko', NULL, 1635, 'Recepción 24 Horas'),
('tokko', 44, 1636, 'Parrilla individual en departamento'),
('tokko', NULL, 1637, 'Patio de juegos'),
('tokko', NULL, 1654, 'Lavarropas'),
('tokko', NULL, 1655, 'Estufa a leña'),
('tokko', NULL, 1656, 'Condominio'),
('tokko', 44, 1657, 'Parrilla techada'),
('tokko', NULL, 1659, 'Cerramiento perimetral'),
('tokko', NULL, 1660, 'Microondas'),
('tokko', NULL, 1661, 'Freezer'),
('tokko', NULL, 1662, 'Heladera'),
('tokko', NULL, 1663, 'Lavavajillas'),
('tokko', NULL, 1664, 'Estacionamiento gratuito'),
('tokko', NULL, 1665, 'Secadora'),
('tokko', NULL, 1667, 'Perimeter alarm'),
('tokko', NULL, 1668, 'Jardinero'),
('tokko', 35, 1671, 'Cancha de Volley'),
('tokko', 35, 1673, 'Cancha de Bochas'),
('tokko', NULL, 1674, 'Cancha de Polo'),
('tokko', 35, 1677, 'Cancha de Paddle'),
('tokko', NULL, 1678, 'Espacio para estacionar'),
('tokko', NULL, 1679, 'Rindex de Soja/hrea'),
('tokko', NULL, 1680, 'Piso'),
('tokko', NULL, 1681, 'Refrigeración Fancoil'),
('tokko', NULL, 1682, 'Refrigeración split'),
('tokko', NULL, 1683, 'Refrigeración Volumen Variable'),
('tokko', NULL, 1684, 'Refrigeración central F/C'),
('tokko', NULL, 1685, 'Refrigeración VRV'),
('tokko', NULL, 1686, 'Refrigeración central propia'),
('tokko', NULL, 1687, 'Refrigeración sectorizada'),
('tokko', NULL, 1688, 'Refrigeración individual'),
('tokko', NULL, 1689, 'Refrigeración individual F/C'),
('tokko', NULL, 1690, 'Refrigeracion No Posee'),
('tokko', NULL, 1691, 'Aire acondicionado individual'),
('tokko', NULL, 1692, 'Calefacción por losa radiante'),
('tokko', NULL, 1693, 'Calefacción por Fancoil'),
('tokko', NULL, 1694, 'Calefaccion No Posee'),
('tokko', NULL, 1695, 'calefacción por aire'),
('tokko', NULL, 1696, 'Calefacción VRV'),
('tokko', NULL, 1697, 'Calefacción tiro balanceado'),
('tokko', NULL, 1698, 'Calefacción F/C'),
('tokko', NULL, 1699, 'Calefacción sectorizada'),
('tokko', NULL, 1700, 'Segmentable'),
('tokko', NULL, 1701, 'Centro de negocios'),
('tokko', NULL, 1702, 'Escaleras de emergencia'),
('tokko', NULL, 1704, 'Detector de metales'),
('tokko', NULL, 1705, 'Tarjetas magnéticas'),
('tokko', NULL, 1706, 'Seguridad digital'),
('tokko', NULL, 1707, 'Local'),
('tokko', NULL, 1710, 'Techos altos'),
('tokko', NULL, 1713, 'Sistema de cableado'),
('tokko', NULL, 1714, 'Grupo electrógeno'),
('tokko', NULL, 1725, 'Tratamiento de efluentes'),
('tokko', NULL, 1730, 'Casco'),
('tokko', NULL, 1731, 'Casa de huéspedes'),
('tokko', NULL, 1732, 'Casa del personal'),
('tokko', NULL, 1733, 'Galpón de herramientas'),
('tokko', NULL, 1734, 'Sobre ripio'),
('tokko', NULL, 1735, 'En asfalto'),
('tokko', NULL, 1736, 'Engorde'),
('tokko', NULL, 1737, 'Tambo'),
('tokko', NULL, 1738, 'Tanque Australiano'),
('tokko', NULL, 1739, 'Apicutura'),
('tokko', NULL, 1740, 'Aves de corral'),
('tokko', NULL, 1741, 'Corrales'),
('tokko', NULL, 1742, 'Horticultura'),
('tokko', NULL, 1743, 'Fruticultura'),
('tokko', NULL, 1744, 'Planta silos'),
('tokko', NULL, 1745, 'Puesto'),
('tokko', NULL, 1746, 'Manga'),
('tokko', NULL, 1747, 'Pista de aterrizaje'),
('tokko', NULL, 1748, 'Teléfono rural'),
('tokko', NULL, 1749, 'Señal celular'),
('tokko', NULL, 1755, 'Molino'),
('tokko', NULL, 1756, 'Potreros'),
('tokko', NULL, 1757, 'Aguadas'),
('tokko', NULL, 1760, 'Bar'),
('tokko', NULL, 1762, 'Pileta descubierta'),
('tokko', NULL, 1763, 'Central telefónica'),
('tokko', NULL, 1764, 'Lavandería'),
('tokko', NULL, 1765, 'Cocina propia'),
('tokko', NULL, 1766, 'Planta de tratamiento de efluentes'),
('tokko', NULL, 1767, 'Salón para niños'),
('tokko', NULL, 1769, 'Categoría'),
('tokko', NULL, 1771, 'Cerco'),
('tokko', NULL, 1772, 'Nivelación'),
('tokko', NULL, 1784, 'Obras Sanitarias'),
('tokko', NULL, 1785, 'Family'),
('tokko', NULL, 1788, 'Amenities'),
('tokko', NULL, 1790, 'Línea blanca'),
('tokko', NULL, 1792, 'Entrada vehicular'),
('tokko', NULL, 1795, 'Al estero'),
('tokko', NULL, 1796, 'Apto gastronómico'),
('tokko', NULL, 1798, 'Exclusividad OLD'),
('tokko', NULL, 1799, 'Barrio privado'),
('tokko', NULL, 1800, 'Cowork'),
('tokko', NULL, 1801, 'Cisterna'),
('tokko', NULL, 1802, 'Roof garden'),
('tokko', NULL, 1804, 'Security totem'),
('tokko', NULL, 1805, 'Sol de la tarde'),
('tokko', NULL, 1806, 'Anexo'),
('tokko', NULL, 1807, 'Pozo artesiano'),
('tokko', NULL, 1808, 'Automatizado'),
('tokko', NULL, 1809, 'Listo para domótica'),
('tokko', NULL, 1811, 'Parrilla de balcón'),
('tokko', NULL, 1812, 'Granero'),
('tokko', NULL, 1813, 'Muebles de baño'),
('tokko', NULL, 1814, 'Bañera'),
('tokko', NULL, 1815, 'Muebles de dormitorio'),
('tokko', NULL, 1816, 'Bicicletero'),
('tokko', NULL, 1817, 'Garaje para lancha'),
('tokko', NULL, 1818, 'Alfombra'),
('tokko', NULL, 1819, 'Ventilador de techo'),
('tokko', NULL, 1820, 'Piso cerámico'),
('tokko', NULL, 1821, 'Vista a la ciudad'),
('tokko', NULL, 1822, 'Interiores de placard'),
('tokko', NULL, 1823, 'Tendedero'),
('tokko', NULL, 1824, 'Piso frío'),
('tokko', NULL, 1825, 'Terraza compartida'),
('tokko', NULL, 1826, 'Anafe'),
('tokko', NULL, 1827, 'Muebles a medida'),
('tokko', NULL, 1828, 'Decorado'),
('tokko', NULL, 1829, 'Persianas eléctricas'),
('tokko', NULL, 1830, 'Cerca eléctrica'),
('tokko', NULL, 1831, 'Portón eléctrico'),
('tokko', NULL, 1832, 'Ducha eléctrica'),
('tokko', NULL, 1833, 'Cerradura electrónica'),
('tokko', NULL, 1835, 'Frente al club'),
('tokko', NULL, 1836, 'Frente al parque'),
('tokko', NULL, 1837, 'Sala familiar'),
('tokko', NULL, 1838, 'Cercado'),
('tokko', NULL, 1841, 'Balcón al frente'),
('tokko', NULL, 1842, 'Salón gourmet'),
('tokko', NULL, 1843, 'Área recreativa planta baja'),
('tokko', NULL, 1844, 'Baranda'),
('tokko', NULL, 1845, 'Piso de madera'),
('tokko', NULL, 1846, 'Red de alta tensión'),
('tokko', NULL, 1848, 'Medidor de agua individual'),
('tokko', NULL, 1849, 'Portero eléctrico'),
('tokko', NULL, 1850, 'Encargado'),
('tokko', 46, 1851, 'Pileta infantil'),
('tokko', NULL, 1852, 'Bajo mesada y alacena'),
('tokko', NULL, 1853, 'A la laguna'),
('tokko', NULL, 1854, 'Piso flotante'),
('tokko', NULL, 1855, 'Artefactos de iluminación'),
('tokko', NULL, 1856, 'Muebles de living'),
('tokko', NULL, 1857, 'Piso de mármol'),
('tokko', NULL, 1858, 'Marina'),
('tokko', NULL, 1860, 'Sol de la mañana'),
('tokko', NULL, 1861, 'Vista a la sierra'),
('tokko', NULL, 1862, 'Luz natural'),
('tokko', NULL, 1863, 'Cerca del subte'),
('tokko', NULL, 1864, 'Junto a la pared'),
('tokko', NULL, 1865, 'Ofuro'),
('tokko', NULL, 1866, 'Horno'),
('tokko', NULL, 1867, 'Vista panorámica'),
('tokko', 58, 1868, 'SUM'),
('tokko', NULL, 1869, 'Pastura'),
('tokko', NULL, 1870, 'Piso de porcelanato'),
('tokko', NULL, 1871, 'Baulera privada en subsuelo'),
('tokko', 46, 1872, 'Pileta privada'),
('tokko', 52, 1873, 'Sauna privado'),
('tokko', NULL, 1874, 'Calle tranquila'),
('tokko', NULL, 1875, 'Piso técnico'),
('tokko', NULL, 1876, 'Rampas'),
('tokko', NULL, 1877, 'Contrafrente'),
('tokko', NULL, 1878, 'Biombo'),
('tokko', NULL, 1879, 'Garita de seguridad'),
('tokko', NULL, 1880, 'Red de seguridad'),
('tokko', NULL, 1881, 'Semiamueblado'),
('tokko', NULL, 1882, 'Muebles de lavadero'),
('tokko', NULL, 1883, 'Mampara'),
('tokko', NULL, 1884, 'Balcón lateral'),
('tokko', NULL, 1885, 'Calefacción solar'),
('tokko', 35, 1886, 'Cancha deportiva'),
('tokko', 35, 1887, 'Cancha de Squash'),
('tokko', NULL, 1888, 'Establo'),
('tokko', NULL, 1889, 'Contrapiso'),
('tokko', NULL, 1890, 'Baldosa podotáctil'),
('tokko', NULL, 1891, 'Transformador'),
('tokko', NULL, 1892, 'Entrada para camiones'),
('tokko', NULL, 1893, 'Vista despejada'),
('tokko', NULL, 1894, 'Piso vinílico'),
('tokko', NULL, 1895, 'Estacionamiento de visitas'),
('tokko', NULL, 1896, 'Entrada de visitas'),
('tokko', NULL, 1897, 'Estructura de pared'),
('tokko', NULL, 1898, 'Placard'),
('tokko', NULL, 1899, 'Cascada'),
('tokko', NULL, 1900, 'Floating floor'),
('tokko', NULL, 1967, 'Administración de Airbnb'),
('tokko', NULL, 2006, 'Terminación en mármol'),
('tokko', NULL, 2007, 'Cocina de porcelana con mesada de granito'),
('tokko', NULL, 2008, 'Bacha de mármol'),
('tokko', NULL, 2009, 'Bacha de vidrio'),
('tokko', NULL, 2010, 'Techo de madera'),
('tokko', NULL, 2011, 'Techo de durlock'),
('tokko', NULL, 2012, 'Techo de yeso'),
('tokko', NULL, 2013, 'Techo de PVC'),
('tokko', NULL, 2014, 'Cielorraso suspendido'),
('tokko', NULL, 2015, 'Piso de granito'),
('tokko', NULL, 2016, 'Piso de mármol'),
('tokko', NULL, 2017, 'Suelo de parquet'),
('tokko', NULL, 2018, 'Piso vinílico'),
('tokko', NULL, 2019, 'Piso de madera flotante'),
('tokko', NULL, 2020, 'Piso de cemento alisado'),
('tokko', NULL, 2021, 'Piso cerámico'),
('tokko', NULL, 2022, 'Piso de pizarra'),
('tokko', NULL, 2023, 'Artefactos de alta gama'),
('tokko', NULL, 2024, 'Muebles de diseño'),
('tokko', NULL, 2025, 'Cortinas automatizadas'),
('tokko', NULL, 2026, 'Cortinas blackout'),
('tokko', NULL, 2027, 'Persianas integradas'),
('tokko', NULL, 2028, 'Vidrio termoacústico'),
('tokko', NULL, 2029, 'Ventanas con reducción de ruido'),
('tokko', NULL, 2030, 'Vista permanente'),
('tokko', NULL, 2031, 'Orientación norte'),
('tokko', NULL, 2032, 'Esquina'),
('tokko', NULL, 2033, 'Triplex'),
('tokko', NULL, 2034, 'Plano flexible'),
('tokko', NULL, 2035, 'Puerta blindada'),
('tokko', NULL, 2036, 'Puerta pivote'),
('tokko', NULL, 2037, 'Puerta maciza'),
('tokko', NULL, 2038, 'Puertas resistentes a impactos'),
('tokko', NULL, 2039, 'Zócalo de madera'),
('tokko', NULL, 2040, 'Zócalo de porcelanato'),
('tokko', NULL, 2041, 'Zócalo laqueado'),
('tokko', NULL, 2044, 'Acceso pavimentado'),
('tokko', NULL, 2045, 'Acceso por teclado'),
('tokko', NULL, 2046, 'Tag de acceso'),
('tokko', NULL, 2047, 'Acceso peatonal'),
('tokko', NULL, 2048, 'Acceso exclusivo para mascotas'),
('tokko', NULL, 2049, 'Acceso exclusivo a la playa'),
('tokko', NULL, 2050, 'Vertedero'),
('tokko', NULL, 2052, 'Garage con amortiguadores de impacto'),
('tokko', NULL, 2055, 'A prueba de polvo'),
('tokko', NULL, 2056, 'Calefón central sin tanque'),
('tokko', NULL, 2057, 'Calefón sin tanque'),
('tokko', NULL, 2059, 'Boxes para caballos'),
('tokko', NULL, 2061, 'Blackout de ventana'),
('tokko', NULL, 2063, 'Locker de playa'),
('tokko', NULL, 2067, 'Vereda'),
('tokko', NULL, 2068, 'Vereda de adoquines'),
('tokko', NULL, 2069, 'Cámara frigorífica'),
('tokko', NULL, 2074, 'Canil'),
('tokko', NULL, 2075, 'Alfombra'),
('tokko', NULL, 2076, 'Molinetes de identificación'),
('tokko', NULL, 2077, 'Cerca de vidrio'),
('tokko', NULL, 2079, 'Fuente'),
('tokko', NULL, 2080, 'Guardería'),
('tokko', NULL, 2081, 'Parrilla a carbón'),
('tokko', NULL, 2084, 'Ducha de playa'),
('tokko', NULL, 2085, 'Bicisenda del condominio'),
('tokko', NULL, 2086, 'Sendero peatonal'),
('tokko', NULL, 2088, 'Tragaluz'),
('tokko', NULL, 2092, 'Techo de vidrio retráctil'),
('tokko', NULL, 2093, 'Recolección selectiva de residuos'),
('tokko', NULL, 2094, 'Barrio cerrado'),
('tokko', NULL, 2095, 'Despensa con muebles'),
('tokko', NULL, 2097, 'Pasillo lateral'),
('tokko', NULL, 2098, 'Baranda de acero inoxidable'),
('tokko', NULL, 2099, 'Espacio de coworking'),
('tokko', NULL, 2102, 'Baulera privada en cochera'),
('tokko', NULL, 2103, 'Ducha bidet'),
('tokko', NULL, 2104, 'Cámara de acceso para vehículos'),
('tokko', NULL, 2105, 'Cámara de acceso social'),
('tokko', NULL, 2106, 'Electrodomésticos'),
('tokko', NULL, 2108, 'Entrada a nivel'),
('tokko', NULL, 2109, 'Entrada lateral'),
('tokko', NULL, 2110, 'Entrada lateral independiente'),
('tokko', NULL, 2111, 'Entrada de visitas'),
('tokko', NULL, 2112, 'Entrada para bañistas'),
('tokko', NULL, 2113, 'Entrada principal'),
('tokko', NULL, 2116, 'Escaleras de granito'),
('tokko', NULL, 2117, 'Escaleras de madera'),
('tokko', NULL, 2118, 'Escaleras de mármol'),
('tokko', NULL, 2119, 'Escalera'),
('tokko', NULL, 2127, 'Espacio web'),
('tokko', NULL, 2129, 'Marcos automatizados'),
('tokko', NULL, 2130, 'Marcos de madera'),
('tokko', NULL, 2131, 'Marcos de PVC'),
('tokko', NULL, 2137, 'Estructura de club completa'),
('tokko', NULL, 2138, 'Invernadero'),
('tokko', NULL, 2139, 'Cerradura biométrica'),
('tokko', NULL, 2140, 'Cerradura digital'),
('tokko', NULL, 2141, 'Cocina'),
('tokko', NULL, 2142, 'Horno a leña'),
('tokko', NULL, 2143, 'Cambiador'),
('tokko', NULL, 2146, 'Gallinero'),
('tokko', NULL, 2147, 'Garaje pintado con epoxi'),
('tokko', NULL, 2148, 'Jardín con parrilla'),
('tokko', NULL, 2151, 'Gazebo'),
('tokko', NULL, 2152, 'Biblioteca de historietas'),
('tokko', NULL, 2153, 'Nivelado'),
('tokko', NULL, 2154, 'Baranda'),
('tokko', NULL, 2155, 'Garita blindada'),
('tokko', NULL, 2159, 'Locker de guardado'),
('tokko', NULL, 2173, 'Interruptores táctiles'),
('tokko', NULL, 2174, 'Exento de consorcio'),
('tokko', NULL, 2175, 'Aislación térmica y acústica'),
('tokko', NULL, 2176, 'Ventana automatizada'),
('tokko', NULL, 2177, 'Ventanal'),
('tokko', NULL, 2178, 'Ventanales grandes'),
('tokko', NULL, 2179, 'Ventanales grandes con cortinas roller'),
('tokko', NULL, 2180, 'Ventanas con persianas eléctricas'),
('tokko', NULL, 2181, 'Chimenea de jardín'),
('tokko', NULL, 2182, 'Chimenea exterior'),
('tokko', NULL, 2184, 'Lavapiés'),
('tokko', NULL, 2185, 'Lavado de autos'),
('tokko', NULL, 2187, 'Lavadero con muebles a medida'),
('tokko', NULL, 2190, 'Araña de techo'),
('tokko', NULL, 2191, 'Luces de emergencia'),
('tokko', NULL, 2192, 'Manta acústica para losa'),
('tokko', NULL, 2193, 'Manta asfáltica para losa'),
('tokko', NULL, 2196, 'A mitad de cuadra'),
('tokko', NULL, 2197, 'Minimercado'),
('tokko', NULL, 2198, 'Mini estanque'),
('tokko', NULL, 2199, 'Mirador'),
('tokko', NULL, 2201, 'Amurallado'),
('tokko', NULL, 2202, 'Pared de vidrio'),
('tokko', NULL, 2203, 'Paredes de vidrio'),
('tokko', NULL, 2205, 'Bañera ofurÃƒÂ´'),
('tokko', NULL, 2206, 'Pared de vidrio reflectivo'),
('tokko', NULL, 2207, 'Paredes aisladas'),
('tokko', NULL, 2208, 'Paredes dobles'),
('tokko', NULL, 2210, 'Pasaplatos para entregas'),
('tokko', NULL, 2213, 'Techo elevado'),
('tokko', NULL, 2214, 'Personal trainer del edificio'),
('tokko', NULL, 2216, 'Pilotis'),
('tokko', NULL, 2217, 'Pintura acrílica'),
('tokko', NULL, 2222, 'Piso antirruido'),
('tokko', NULL, 2223, 'Piso de goma'),
('tokko', NULL, 2224, 'Piso de madera entablonada'),
('tokko', NULL, 2230, 'Parrilla para pizza'),
('tokko', NULL, 2232, 'Pozo'),
('tokko', NULL, 2236, 'Huerta'),
('tokko', NULL, 2238, 'Porte-cochÃƒÂ¨re'),
('tokko', NULL, 2239, 'Portón con cámara de acceso'),
('tokko', NULL, 2240, 'Portón electrónico'),
('tokko', NULL, 2241, 'Puertas con reducción de ruido'),
('tokko', NULL, 2242, 'Puertas con burletes'),
('tokko', NULL, 2243, 'Puertas laqueadas'),
('tokko', NULL, 2244, 'Potencial constructivo'),
('tokko', NULL, 2245, 'Plaza boulevard'),
('tokko', NULL, 2246, 'Plaza social'),
('tokko', NULL, 2247, 'Edificio revestido en cerámico'),
('tokko', NULL, 2251, 'Piso entablonado'),
('tokko', NULL, 2267, 'Quincho con parrilla'),
('tokko', NULL, 2268, 'Quincho gourmet'),
('tokko', NULL, 2269, 'Quinchos'),
('tokko', NULL, 2270, 'Cielorraso de yeso suspendido'),
('tokko', NULL, 2271, 'Reconocimiento facial'),
('tokko', NULL, 2273, 'Red de seguridad en ventanas'),
('tokko', NULL, 2275, 'Reforestación'),
('tokko', NULL, 2276, 'Reservas'),
('tokko', NULL, 2277, 'Restaurante privado'),
('tokko', NULL, 2279, 'Zócalos de poliestireno'),
('tokko', NULL, 2280, 'Balcón con parrilla'),
('tokko', NULL, 2297, 'Sala con balcón'),
('tokko', NULL, 2300, 'Moldura de yeso'),
('tokko', NULL, 2305, 'Sensor de presencia en cochera'),
('tokko', NULL, 2316, 'Bacha de lavadero'),
('tokko', NULL, 2317, 'Bacha de cocina auxiliar'),
('tokko', NULL, 2318, 'Acuario'),
('tokko', NULL, 2319, 'Estanque de peces'),
('tokko', NULL, 2320, 'Teja galvanizada'),
('tokko', NULL, 2321, 'Techo de teja'),
('tokko', NULL, 2322, 'Tejas de policarbonato'),
('tokko', NULL, 2323, 'Tejas de cemento'),
('tokko', NULL, 2330, 'Techo retráctil'),
('tokko', NULL, 2331, 'Techo retráctil automatizado'),
('tokko', NULL, 2333, 'Toallero eléctrico'),
('tokko', NULL, 2334, 'Toma para bicicleta eléctrica'),
('tokko', NULL, 2335, 'Tomas USB'),
('tokko', NULL, 2338, 'Turismo rural'),
('tokko', NULL, 2339, 'Espacio de carga y descarga'),
('tokko', NULL, 2340, 'Espacio de embarque'),
('tokko', NULL, 2342, 'Espacio(s) para motocicletas'),
('tokko', NULL, 2344, 'Balcón con jacuzzi'),
('tokko', NULL, 2345, 'Balcón con pileta'),
('tokko', NULL, 2346, 'Balcón gourmet'),
('tokko', NULL, 2347, 'Ventilación natural'),
('tokko', NULL, 2348, 'Carril de desaceleración'),
('tokko', NULL, 2349, 'Vidrio de alta calidad'),
('tokko', NULL, 2350, 'Aviario'),
('tokko', NULL, 2351, 'Ajedrez gigante')


